export type RiskLevel = 'green' | 'yellow' | 'orange' | 'red'
export type StormSeverity = 'weak' | 'moderate' | 'strong' | 'severe'

export interface Me {
  id: string
  tenant_id: string
  email: string
  full_name: string | null
  role: string
  is_active: boolean
  is_platform_admin: boolean
  created_at: string
  storm_module_enabled: boolean
  agro_module_enabled: boolean
  // Informativo, nunca bloqueia login — dirige o banner "confirme seu
  // e-mail" (item 5, paridade com web/src/types.ts's Me).
  email_verified: boolean
}

export interface LocationItem {
  id: string
  name: string
  kind: string
  latitude: number
  longitude: number
  radius_km: number
  is_active: boolean
  created_at: string
  // Talhão support (FASE 26, ADR-0022) — present → this location is a plot
  // inside the parent farm (`parent_location_id`), and `crop` is a
  // free-form culture label (soja, milho, café...).
  parent_location_id: string | null
  crop: string | null
  // Visual-only polygon outline (FASE 27, ADR-0024) — a GeoJSON Polygon
  // serialized as a JSON string. Never used for weather/agro lookups.
  boundary_geojson: string | null
  // Manual color override (FASE 27, ADR-0025) — when `null`, the map
  // derives a color from `crop` instead (`cropColor()`).
  color: string | null
}

export interface StormRisk {
  id: string
  location_id: string
  severity: RiskLevel
  rain_risk: number
  wind_risk: number
  hail_risk: number
  lightning_risk: number
  storm_distance_km: number | null
  storm_speed_kmh: number | null
  eta_minutes: number | null
  is_mock: boolean
  experimental: boolean
  // FASE 9 (ADR-0060) — null quando ANTHROPIC_API_KEY não está
  // configurada, a geração ainda não rodou, ou a severidade é "green".
  ai_summary: string | null
}

// NDVI per talhão (FASE 29, ADR-0053) — only ever meaningful for a plot
// with a drawn boundary.
export interface NdviReading {
  observed_at: string
  ndvi_mean: number | null
  valid_pixel_percent: number
  is_mock: boolean
}

// One INPE DETER/PRODES alert intersecting a talhão's drawn boundary.
export interface DeforestationAlert {
  source: string // "DETER-AMZ" | "PRODES-CERRADO"
  classname: string
  detected_at: string | null
  area_ha: number | null
  municipio: string | null
  uf: string | null
}

export interface DeforestationCheck {
  checked_sources: string[]
  last_checked_at: string | null
  alerts: DeforestationAlert[]
}

// Regional soil-wetness context from NASA POWER — a model-based estimate
// (~50km native resolution), never a per-talhão measurement like NDVI.
export interface SoilMoisture {
  observed_at: string
  surface_wetness_percent: number
  root_zone_wetness_percent: number
  profile_wetness_percent: number
  is_mock: boolean
}

// Last Alert of one event type (frost/dry-spell) — deliberately
// historical, not a computed risk level: `null` on RiskDigest means "no
// alert of this type has ever fired here", never "safe now" (Fase 3-A,
// ADR-0087).
export interface LastAlert {
  occurred_at: string
  level: RiskLevel
  title: string
  message: string
}

// Aggregates every risk signal already computed/persisted for one
// location into a single read (GET /locations/:id/risk-digest, Fase 3-A,
// ADR-0087) — nothing here is recalculated. ZARC is deliberately excluded
// (live geocoding lookup, not a persisted per-location signal).
export interface RiskDigest {
  location_id: string
  generated_at: string
  storm: StormRisk | null
  ndvi: NdviReading | null
  deforestation: DeforestationCheck | null
  frost_last_alert: LastAlert | null
  dry_spell_last_alert: LastAlert | null
  soil_moisture: SoilMoisture | null
}

// Deterministic risk→action recommendation, generated by the fixed
// catalog in backend/engine/recommendations.py (Fase 5, ADR-0089) — never
// an LLM deciding the action. `alert_id` links to the Alert that
// accompanies it, when one exists for the same day; `null` is normal.
export interface RecommendedAction {
  id: string
  location_id: string
  rule_key: string
  title: string
  message: string
  level: RiskLevel
  alert_id: string | null
  created_at: string
}

// Caderno de Campo (Fase 6, ADR-0090). `version` is used for optimistic
// concurrency — an update must send the `base_version` it last saw; the
// backend 409s instead of overwriting silently when it's stale.
export type FieldOccurrenceStatus = 'open' | 'resolved'
export type FieldTaskStatus = 'pending' | 'in_progress' | 'done' | 'cancelled'

export interface FieldOccurrence {
  id: string
  location_id: string
  alert_id: string | null
  recommended_action_id: string | null
  category: string
  description: string
  latitude: number
  longitude: number
  status: FieldOccurrenceStatus
  reported_by: string
  reported_at: string
  version: number
}

export interface Inspection {
  id: string
  location_id: string
  occurrence_id: string | null
  notes: string
  latitude: number | null
  longitude: number | null
  inspected_by: string
  inspected_at: string
  version: number
}

export interface FieldPhoto {
  id: string
  inspection_id: string
  content_type: string
  size_bytes: number
  uploaded_by: string
  uploaded_at: string
  // Short-lived signed URL — never public/permanent (ADR-0090).
  url: string
}

export interface FieldTask {
  id: string
  location_id: string
  occurrence_id: string | null
  alert_id: string | null
  recommended_action_id: string | null
  title: string
  description: string | null
  assigned_to: string | null
  due_at: string | null
  status: FieldTaskStatus
  completed_by: string | null
  completed_at: string | null
  version: number
}

export interface FieldTimelineEntry {
  kind: 'occurrence' | 'inspection' | 'task' | 'alert'
  ref_id: string
  occurred_at: string
  title: string
  summary: string
}

export interface StormCell {
  id: string
  detected_at: string
  latitude: number
  longitude: number
  severity: StormSeverity
  max_reflectivity: number | null
  average_reflectivity: number | null
  area_km2: number | null
  is_mock: boolean
}

export interface LightningStrike {
  id: string
  detected_at: string
  latitude: number
  longitude: number
  is_mock: boolean
}

export interface SatelliteImageMeta {
  id: string
  captured_at: string
  bbox: [number, number, number, number]
  band: string
  width: number
  height: number
}

export interface ConvectiveWatch {
  id: string
  first_detected_at: string
  detected_at: string
  latitude: number
  longitude: number
  min_brightness_temp_k: number
  area_km2: number | null
  speed_kmh: number | null
  direction_deg: number | null
  is_active: boolean
  is_mock: boolean
  experimental: boolean
}

export interface AlertItem {
  id: string
  location_id: string
  event_type: string
  level: RiskLevel
  title: string
  message: string
  created_at: string
}

export interface ForecastPoint {
  time: string
  temperature_c: number | null
  temperature_min_c: number | null
  precipitation_probability: number | null
  precipitation_mm: number | null
  // Open-Meteo-exclusive (FASE 25, ADR-0021) — other sources leave these
  // `null`, never approximated from something else.
  temperature_mean_c: number | null
  humidity_mean_percent: number | null
  humidity_max_percent: number | null
  wind_gusts_max_kmh: number | null
  evapotranspiration_mm: number | null
  cape_max_jkg: number | null
}

export interface Forecast {
  provenance: Provenance
  latitude: number
  longitude: number
  points: ForecastPoint[]
}

export interface SprayWindow {
  wind_kmh: number | null
  wind_gusts_kmh: number | null
  max_wind_kmh: number
  rain_probability_percent: number | null
  rain_expected_mm: number | null
  max_rain_probability_percent: number
  humidity_percent: number | null
  inversion_risk: boolean
  safe: boolean | null
}

export interface DailyRainfall {
  date: string
  total_mm: number
}

export interface RainfallHistory {
  latitude: number
  longitude: number
  daily: DailyRainfall[]
}

export interface Provenance {
  source_name: string
  source_kind: string
  is_mock: boolean
}

export interface CurrentConditions {
  provenance: Provenance
  observed_at: string
  latitude: number
  longitude: number
  temperature_c: number | null
  wind_kmh: number | null
  wind_gusts_kmh: number | null
  precipitation_mm: number | null
}

export interface CitySearchResult {
  label: string
  latitude: number
  longitude: number
}

export interface CreateLocationInput {
  name: string
  kind?: string
  latitude: number
  longitude: number
  radius_km?: number
  parent_location_id?: string
  crop?: string
  boundary_geojson?: string
  color?: string
}

export interface UpdateLocationInput {
  name?: string
  kind?: string
  latitude?: number
  longitude?: number
  radius_km?: number
  is_active?: boolean
  crop?: string
  boundary_geojson?: string
  color?: string
}

export interface PrecipitationError {
  bias_mm: number
  mae_mm: number
  sample_count: number
}

export interface ModelMetrics {
  model: string
  sample_count: number
  has_enough_samples: boolean
  temperature_mae_c: number | null
  precipitation: PrecipitationError | null
  wind_mae_kmh: number | null
  rain_hit_rate: number | null
  brier_score: number | null
}

export interface ForecastComparison {
  location_id: string
  min_sample_size: number
  models: ModelMetrics[]
}

export type OrganizationRole = 'owner' | 'admin' | 'agronomist' | 'operator' | 'viewer'

export interface Organization {
  id: string
  name: string
  slug: string
}

export interface OrganizationMember {
  id: string
  email: string
  full_name: string | null
  role: OrganizationRole
  is_active: boolean
  organization_wide_access: boolean
  access_expires_at: string | null
  created_at: string
}

export interface OrganizationInvitation {
  id: string
  email: string
  role: OrganizationRole
  location_id: string | null
  expires_at: string
  access_expires_at: string | null
  accepted_at: string | null
  revoked_at: string | null
  created_at: string
}

export type VegetationIndex = 'ndvi' | 'ndre' | 'evi' | 'ndmi' | 'ndwi'

export interface VegetationReading {
  id: string
  observed_at: string
  index_name: VegetationIndex
  value_mean: number
  source_name: string
  valid_pixel_percent: number
  cloud_cover_percent: number
  quality: 'high' | 'medium' | 'low'
  reliable: boolean
  vigor_zones: Array<{
    label: string
    min_value: number
    max_value: number
    pixel_percent: number
  }>
  is_mock: boolean
}

export interface VegetationSeries {
  location_id: string
  index_name: VegetationIndex
  current: VegetationReading | null
  series: VegetationReading[]
  anomaly: {
    status: 'insufficient_history' | 'below_expected' | 'normal' | 'above_expected'
    minimum_history: number
    baseline_count: number
    baseline_mean: number | null
    difference: number | null
    percent_difference: number | null
    z_score: number | null
  }
  persistent_drop: boolean
}
