"""bootstrap schema: enable PostGIS and create initial tables

This first ("bootstrap") migration enables the PostGIS extension and creates
the full FASE 2 schema from the model metadata. Subsequent phases use normal
incremental (autogenerated) migrations that diff against the live database.

Revision ID: 0001_bootstrap
Revises:
Create Date: 2026-08-19
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

from app import models  # noqa: F401  # ensure all models are registered
from app.db.base import Base

revision: str = "0001_bootstrap"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
    # PostGIS extension is intentionally left in place on downgrade.
