"""add forecast_snapshots (Fase 2 — Comparação e Validação de Previsões)

Revision ID: 08c0fdcd06e8
Revises: ad53f9776b9b
Create Date: 2026-09-05 18:00:00.000000

Hand-written (not autogenerated), same idiom as every other migration in
this project. Guarded with an existence check — ``0001_bootstrap`` builds
from the *live* ORM models, so on a fresh database this table already
exists. Tenant-scoped from the start (RLS policy created in this same
migration, per the project's own rule — see ``docs/ROADMAP_IMPLEMENTACAO.md``
principles list): ``ENABLE``/``FORCE``/``CREATE POLICY`` right after the
table, same sequence as ``d4b8e2f6a9c1``/``e884730e20e4``/``b3f7d1a6e2c8``.
No new GRANT needed — the RLS migration (``0b7b9a5dbd11``) already set
``ALTER DEFAULT PRIVILEGES`` for any future table.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import inspect

revision: str = "08c0fdcd06e8"
down_revision: str | None = "ad53f9776b9b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_CREATE_POLICY_SQL = """
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE tablename = 'forecast_snapshots' AND policyname = 'tenant_isolation'
    ) THEN
        EXECUTE 'CREATE POLICY tenant_isolation ON forecast_snapshots
            USING (
                current_setting(''app.bypass_rls'', true) = ''on''
                OR tenant_id = NULLIF(current_setting(''app.tenant_id'', true), '''')::uuid
            )
            WITH CHECK (
                current_setting(''app.bypass_rls'', true) = ''on''
                OR tenant_id = NULLIF(current_setting(''app.tenant_id'', true), '''')::uuid
            )';
    END IF;
END $$;
"""


def upgrade() -> None:
    inspector = inspect(op.get_bind())
    if "forecast_snapshots" not in inspector.get_table_names():
        op.create_table(
            "forecast_snapshots",
            sa.Column("id", sa.Uuid(), primary_key=True),
            sa.Column(
                "tenant_id",
                sa.Uuid(),
                sa.ForeignKey("tenants.id", ondelete="CASCADE"),
                nullable=False,
                index=True,
            ),
            sa.Column(
                "location_id",
                sa.Uuid(),
                sa.ForeignKey("locations.id", ondelete="CASCADE"),
                nullable=False,
                index=True,
            ),
            sa.Column("provider", sa.String(length=40), nullable=False),
            sa.Column("model", sa.String(length=40), nullable=False, index=True),
            sa.Column("target_date", sa.Date(), nullable=False, index=True),
            sa.Column("horizon_hours", sa.Integer(), nullable=False),
            sa.Column("snapshot_taken_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("temperature_max_predicted_c", sa.Float(), nullable=True),
            sa.Column("precipitation_predicted_mm", sa.Float(), nullable=True),
            sa.Column("precipitation_probability_percent", sa.Float(), nullable=True),
            sa.Column("wind_gusts_predicted_kmh", sa.Float(), nullable=True),
            sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("temperature_max_observed_c", sa.Float(), nullable=True),
            sa.Column("precipitation_observed_mm", sa.Float(), nullable=True),
            sa.Column("wind_gusts_observed_kmh", sa.Float(), nullable=True),
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.func.now(),
                nullable=False,
            ),
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                server_default=sa.func.now(),
                nullable=False,
            ),
            sa.UniqueConstraint(
                "location_id",
                "provider",
                "model",
                "target_date",
                "horizon_hours",
                name="uq_forecast_snapshot_location_provider_model_date_horizon",
            ),
        )

    op.execute("ALTER TABLE forecast_snapshots ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE forecast_snapshots FORCE ROW LEVEL SECURITY")
    op.execute(_CREATE_POLICY_SQL)


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON forecast_snapshots")
    op.execute("ALTER TABLE forecast_snapshots NO FORCE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE forecast_snapshots DISABLE ROW LEVEL SECURITY")
    op.drop_table("forecast_snapshots")
