"""add lightning_strikes

Revision ID: 6ad9dda7d22c
Revises: d3e8f1a9c7b2
Create Date: 2026-08-20 22:00:00.000000

Hand-written (not autogenerated) — same reason as the other migrations in
this project (PostGIS "tiger geocoder" noise). Guarded with an existence
check — same reason as ``b7d4e1f9a2c3``: ``0001_bootstrap`` builds from the
*live* ORM models, so on a fresh database it already creates this table.
See ADR-0012 and ADR-0019 (API-REDEMET STSC).
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import inspect

revision: str = "6ad9dda7d22c"
down_revision: str | None = "d3e8f1a9c7b2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    if inspect(op.get_bind()).has_table("lightning_strikes"):
        return
    op.create_table(
        "lightning_strikes",
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("is_mock", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_lightning_strikes_detected_at"), "lightning_strikes", ["detected_at"], unique=False
    )


def downgrade() -> None:
    op.drop_index(op.f("ix_lightning_strikes_detected_at"), table_name="lightning_strikes")
    op.drop_table("lightning_strikes")
