"""add alert_rules tables (Fase 3 — Alertas Personalizados, ADR-0083)

Revision ID: 7e8060f3f148
Revises: 67c40c366af6
Create Date: 2026-09-05 21:05:00.000000

Eight tenant-scoped tables, additive alongside Alert/Notification/
AlertPreference (untouched) — see app/alert_rules/models.py module
docstring for what each is. Hand-written (not autogenerated), same idiom
as every other migration in this project. Guarded with an existence check
per table — ``0001_bootstrap`` builds from the *live* ORM models, so on a
fresh database these tables already exist. RLS policy created in this same
migration for every table (project rule: never create a tenant-scoped
table without RLS from the start) — same ENABLE/FORCE/CREATE POLICY
sequence as every other tenant-scoped table added since ``0b7b9a5dbd11``.
No new GRANT needed — that migration already set ALTER DEFAULT PRIVILEGES.

Table names interpolated into the DDL below (``_policy_sql``/``_enable_rls``/
``_disable_rls``) all come from the fixed, hardcoded ``_TABLES`` tuple in
this file — never from user/request input — same pattern already used by
every RLS-enabling migration in this project (e.g. ``08c0fdcd06e8``,
``b3f7d1a6e2c8``), just factored into a helper here since there are eight
tables instead of one.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import inspect
from sqlalchemy.dialects.postgresql import ENUM as PGEnum

revision: str = "7e8060f3f148"
down_revision: str | None = "67c40c366af6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_TABLES = (
    "alert_rules",
    "alert_conditions",
    "alert_channels",
    "alert_recipients",
    "alert_events",
    "alert_deliveries",
    "alert_acknowledgements",
    "alert_escalations",
)


def _policy_sql(table: str) -> str:
    # nosec: `table` is always one of the hardcoded literals in _TABLES
    # above, never external input — see module docstring.
    return f"""
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE tablename = '{table}' AND policyname = 'tenant_isolation'
    ) THEN
        EXECUTE 'CREATE POLICY tenant_isolation ON {table}
            USING (
                current_setting(''app.bypass_rls'', true) = ''on''
                OR tenant_id = NULLIF(current_setting(''app.tenant_id'', true), '''')::uuid
            )
            WITH CHECK (
                current_setting(''app.bypass_rls'', true) = ''on''
                OR tenant_id = NULLIF(current_setting(''app.tenant_id'', true), '''')::uuid
            )';
    END IF;
END $$;
"""


def _enable_rls(table: str) -> None:
    # nosec: `table` is always one of the hardcoded literals in _TABLES.
    op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
    op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
    op.execute(_policy_sql(table))


def _disable_rls(table: str) -> None:
    # nosec: `table` is always one of the hardcoded literals in _TABLES.
    op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
    op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
    op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")


def _tenant_id_col() -> sa.Column:
    return sa.Column(
        "tenant_id",
        sa.Uuid(),
        sa.ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )


def _timestamps() -> list[sa.Column]:
    return [
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
    ]


def _existing_type(name: str) -> PGEnum:
    """Reference (never (re)create) an already-existing Postgres enum type
    — the plain ``sa.Enum(..., create_type=False)`` still tried to emit
    ``CREATE TYPE`` for a bare column DDL outside of an ORM-bound MetaData
    (confirmed live: ``notification_channel``/``notification_status`` are
    already created by ``0001_bootstrap`` and earlier migrations); the
    dialect-specific ``postgresql.ENUM`` with ``create_type=False`` is the
    documented way to avoid that."""
    return PGEnum(name=name, create_type=False)


def upgrade() -> None:
    bind = op.get_bind()
    inspector = inspect(bind)
    existing = set(inspector.get_table_names())

    alert_event_status = PGEnum("OPEN", "UPDATED", "CLOSED", name="alert_event_status")
    alert_event_status.create(bind, checkfirst=True)

    if "alert_rules" not in existing:
        op.create_table(
            "alert_rules",
            sa.Column("id", sa.Uuid(), primary_key=True),
            _tenant_id_col(),
            sa.Column(
                "location_id",
                sa.Uuid(),
                sa.ForeignKey("locations.id", ondelete="CASCADE"),
                nullable=False,
                index=True,
            ),
            sa.Column(
                "user_id",
                sa.Uuid(),
                sa.ForeignKey("users.id", ondelete="CASCADE"),
                nullable=False,
                index=True,
            ),
            sa.Column("name", sa.String(length=120), nullable=False),
            sa.Column("enabled", sa.Boolean(), nullable=False, server_default=sa.true()),
            sa.Column("lead_time_minutes", sa.Integer(), nullable=False, server_default="0"),
            sa.Column("quiet_hours_start", sa.Time(), nullable=True),
            sa.Column("quiet_hours_end", sa.Time(), nullable=True),
            sa.Column("cooldown_minutes", sa.Integer(), nullable=False, server_default="0"),
            sa.Column("last_fired_at", sa.DateTime(timezone=True), nullable=True),
            *_timestamps(),
        )

    if "alert_conditions" not in existing:
        op.create_table(
            "alert_conditions",
            sa.Column("id", sa.Uuid(), primary_key=True),
            _tenant_id_col(),
            sa.Column(
                "rule_id",
                sa.Uuid(),
                sa.ForeignKey("alert_rules.id", ondelete="CASCADE"),
                nullable=False,
                index=True,
            ),
            sa.Column("metric", sa.String(length=40), nullable=False),
            sa.Column("operator", sa.String(length=4), nullable=False),
            sa.Column("threshold", sa.Float(), nullable=False),
            sa.Column("group_index", sa.Integer(), nullable=False, server_default="0"),
            *_timestamps(),
        )

    if "alert_channels" not in existing:
        op.create_table(
            "alert_channels",
            sa.Column("id", sa.Uuid(), primary_key=True),
            _tenant_id_col(),
            sa.Column(
                "kind",
                _existing_type("notification_channel"),
                nullable=False,
            ),
            sa.Column("name", sa.String(length=120), nullable=False),
            sa.Column("enabled", sa.Boolean(), nullable=False, server_default=sa.true()),
            sa.Column("webhook_url", sa.String(length=500), nullable=True),
            sa.Column("webhook_secret_encrypted", sa.Text(), nullable=True),
            sa.Column("phone_number", sa.String(length=32), nullable=True),
            *_timestamps(),
        )

    if "alert_recipients" not in existing:
        op.create_table(
            "alert_recipients",
            sa.Column("id", sa.Uuid(), primary_key=True),
            _tenant_id_col(),
            sa.Column(
                "rule_id",
                sa.Uuid(),
                sa.ForeignKey("alert_rules.id", ondelete="CASCADE"),
                nullable=False,
                index=True,
            ),
            sa.Column(
                "channel_id",
                sa.Uuid(),
                sa.ForeignKey("alert_channels.id", ondelete="CASCADE"),
                nullable=False,
                index=True,
            ),
            sa.Column(
                "user_id",
                sa.Uuid(),
                sa.ForeignKey("users.id", ondelete="CASCADE"),
                nullable=True,
                index=True,
            ),
            sa.Column("enabled", sa.Boolean(), nullable=False, server_default=sa.true()),
            *_timestamps(),
        )

    if "alert_events" not in existing:
        op.create_table(
            "alert_events",
            sa.Column("id", sa.Uuid(), primary_key=True),
            _tenant_id_col(),
            sa.Column(
                "rule_id",
                sa.Uuid(),
                sa.ForeignKey("alert_rules.id", ondelete="CASCADE"),
                nullable=False,
                index=True,
            ),
            sa.Column(
                "location_id",
                sa.Uuid(),
                sa.ForeignKey("locations.id", ondelete="CASCADE"),
                nullable=False,
                index=True,
            ),
            sa.Column(
                "alert_id",
                sa.Uuid(),
                sa.ForeignKey("alerts.id", ondelete="SET NULL"),
                nullable=True,
                index=True,
            ),
            sa.Column(
                "status",
                _existing_type("alert_event_status"),
                nullable=False,
                server_default="OPEN",
            ),
            sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("last_updated_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("snapshot_json", sa.Text(), nullable=False),
            *_timestamps(),
        )

    if "alert_deliveries" not in existing:
        op.create_table(
            "alert_deliveries",
            sa.Column("id", sa.Uuid(), primary_key=True),
            _tenant_id_col(),
            sa.Column(
                "event_id",
                sa.Uuid(),
                sa.ForeignKey("alert_events.id", ondelete="CASCADE"),
                nullable=False,
                index=True,
            ),
            sa.Column(
                "recipient_id",
                sa.Uuid(),
                sa.ForeignKey("alert_recipients.id", ondelete="CASCADE"),
                nullable=False,
                index=True,
            ),
            sa.Column(
                "notice_kind",
                _existing_type("alert_event_status"),
                nullable=False,
            ),
            sa.Column(
                "channel_kind",
                _existing_type("notification_channel"),
                nullable=False,
            ),
            sa.Column(
                "status",
                _existing_type("notification_status"),
                nullable=False,
                server_default="PENDING",
            ),
            sa.Column("attempts", sa.Integer(), nullable=False, server_default="0"),
            sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("error", sa.Text(), nullable=True),
            *_timestamps(),
        )

    if "alert_acknowledgements" not in existing:
        op.create_table(
            "alert_acknowledgements",
            sa.Column("id", sa.Uuid(), primary_key=True),
            _tenant_id_col(),
            sa.Column(
                "event_id",
                sa.Uuid(),
                sa.ForeignKey("alert_events.id", ondelete="CASCADE"),
                nullable=False,
                index=True,
            ),
            sa.Column(
                "acknowledged_by",
                sa.Uuid(),
                sa.ForeignKey("users.id", ondelete="CASCADE"),
                nullable=False,
            ),
            sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("notes", sa.Text(), nullable=True),
            *_timestamps(),
            sa.UniqueConstraint("event_id", name="uq_alert_ack_event"),
        )

    if "alert_escalations" not in existing:
        op.create_table(
            "alert_escalations",
            sa.Column("id", sa.Uuid(), primary_key=True),
            _tenant_id_col(),
            sa.Column(
                "rule_id",
                sa.Uuid(),
                sa.ForeignKey("alert_rules.id", ondelete="CASCADE"),
                nullable=False,
                index=True,
            ),
            sa.Column("step_order", sa.Integer(), nullable=False, server_default="0"),
            sa.Column("delay_minutes", sa.Integer(), nullable=False),
            sa.Column(
                "recipient_id",
                sa.Uuid(),
                sa.ForeignKey("alert_recipients.id", ondelete="CASCADE"),
                nullable=False,
            ),
            sa.Column("enabled", sa.Boolean(), nullable=False, server_default=sa.true()),
            *_timestamps(),
        )

    for table in _TABLES:
        _enable_rls(table)


def downgrade() -> None:
    for table in reversed(_TABLES):
        _disable_rls(table)
    # Drop children before parents (FK order).
    for table in reversed(_TABLES):
        op.drop_table(table)
    op.execute("DROP TYPE IF EXISTS alert_event_status")
