"""add tenants.storm_enabled / tenants.agro_enabled

Revision ID: 817b1b97cac3
Revises: d7b1f4a8c2e6
Create Date: 2026-08-24 18:00:00.000000

Hand-written (not autogenerated) — same reason as the other migrations in
this project (PostGIS "tiger geocoder" noise). Guarded with an existence
check — same reason as ``c4a8f2d6e9b3``: ``0001_bootstrap`` builds from the
*live* ORM models, so on a fresh database these columns already exist.

Module selection (Tempestade and/or Agro), chosen at registration —
existing tenants get ``storm_enabled=True`` *and* ``agro_enabled=True``:
both modules were already available to every tenant before this flag
existed, so this is a grandfather backfill, not a behavior change for
anyone already registered. Only *new* registrations from here on default
`agro_module` to unchecked (an explicit opt-in) — that default lives in
``RegisterIn``/the signup form, not in this column's server default.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import inspect

revision: str = "817b1b97cac3"
down_revision: str | None = "d7b1f4a8c2e6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    inspector = inspect(op.get_bind())
    existing = {c["name"] for c in inspector.get_columns("tenants")}
    if "storm_enabled" not in existing:
        op.add_column(
            "tenants",
            sa.Column("storm_enabled", sa.Boolean(), nullable=False, server_default=sa.true()),
        )
    if "agro_enabled" not in existing:
        op.add_column(
            "tenants",
            # true, not false: grandfathers existing tenants in (see module
            # docstring) — new registrations still default agro_module to
            # unchecked, but that's decided in RegisterIn, not here.
            sa.Column("agro_enabled", sa.Boolean(), nullable=False, server_default=sa.true()),
        )


def downgrade() -> None:
    op.drop_column("tenants", "agro_enabled")
    op.drop_column("tenants", "storm_enabled")
