"""add users.is_platform_admin

Revision ID: a1c8e5f3d7b2
Revises: e5f7a3c9b1d2
Create Date: 2026-08-23 19:00:00.000000

Hand-written (not autogenerated) — same reason as the other migrations in
this project (PostGIS "tiger geocoder" noise). Guarded with an existence
check — same reason as ``d4f8b2e6c9a3``: ``0001_bootstrap`` builds from the
*live* ORM models, so on a fresh database this column already exists. See
ADR-0048 (cross-tenant platform admin panel, FASE 28).
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import inspect

revision: str = "a1c8e5f3d7b2"
down_revision: str | None = "e5f7a3c9b1d2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    inspector = inspect(op.get_bind())
    if "is_platform_admin" not in {c["name"] for c in inspector.get_columns("users")}:
        op.add_column(
            "users",
            sa.Column(
                "is_platform_admin",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            ),
        )


def downgrade() -> None:
    op.drop_column("users", "is_platform_admin")
