"""add locations.soil_type

Revision ID: a3c7e9f1b4d6
Revises: e7f1a3c5b9d2
Create Date: 2026-08-27 15:00:00.000000

Hand-written (not autogenerated) — same reason as the other migrations in
this project (PostGIS "tiger geocoder" noise). Guarded with an existence
check — ``0001_bootstrap`` builds from the *live* ORM models, so on a
fresh database this column already exists. See ADR-0069 (ZARC planting
window, item 1 — soil texture class needed to match a talhão against the
right ZARC row).
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import inspect

revision: str = "a3c7e9f1b4d6"
down_revision: str | None = "e7f1a3c5b9d2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    inspector = inspect(op.get_bind())
    if "soil_type" not in {c["name"] for c in inspector.get_columns("locations")}:
        op.add_column("locations", sa.Column("soil_type", sa.String(length=20), nullable=True))


def downgrade() -> None:
    op.drop_column("locations", "soil_type")
