"""add expo push support to push_subscriptions

Revision ID: a3e8d1c6f4b2
Revises: f2a7c4e9b1d6
Create Date: 2026-08-21 21:00:00.000000

Hand-written (not autogenerated) — same reason as the other migrations in
this project (PostGIS "tiger geocoder" noise). Guarded with existence
checks — same reason as ``5e36b6016c06``: ``0001_bootstrap`` builds from
the *live* ORM models, so on a fresh database these columns already exist
and ``endpoint``/``p256dh``/``auth`` are already nullable. See ADR-0023
(mobile app parity, FASE 26).
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import inspect

revision: str = "a3e8d1c6f4b2"
down_revision: str | None = "f2a7c4e9b1d6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    inspector = inspect(op.get_bind())
    columns = {c["name"]: c for c in inspector.get_columns("push_subscriptions")}

    if "platform" not in columns:
        op.add_column(
            "push_subscriptions",
            sa.Column("platform", sa.String(length=20), nullable=False, server_default="web"),
        )
        op.alter_column("push_subscriptions", "platform", server_default=None)

    if "expo_push_token" not in columns:
        op.add_column("push_subscriptions", sa.Column("expo_push_token", sa.Text(), nullable=True))
        op.create_unique_constraint(
            "uq_push_subscriptions_expo_push_token", "push_subscriptions", ["expo_push_token"]
        )

    if "endpoint" in columns and not columns["endpoint"]["nullable"]:
        op.alter_column("push_subscriptions", "endpoint", nullable=True)
    if "p256dh" in columns and not columns["p256dh"]["nullable"]:
        op.alter_column("push_subscriptions", "p256dh", nullable=True)
    if "auth" in columns and not columns["auth"]["nullable"]:
        op.alter_column("push_subscriptions", "auth", nullable=True)


def downgrade() -> None:
    # Hardening ADR-0031: on a database bootstrapped from the frozen-DDL
    # baseline (0001_bootstrap), this column's unique constraint was created
    # by the ORM's ``unique=True`` and got Postgres's own auto-generated
    # name (``push_subscriptions_expo_push_token_key``), not the hand-picked
    # name this migration's upgrade() used to create it
    # (``uq_push_subscriptions_expo_push_token``) — that branch of upgrade()
    # is skipped entirely whenever the column already exists. Look the
    # constraint up by column instead of assuming either fixed name.
    inspector = inspect(op.get_bind())
    op.alter_column("push_subscriptions", "auth", nullable=False)
    op.alter_column("push_subscriptions", "p256dh", nullable=False)
    op.alter_column("push_subscriptions", "endpoint", nullable=False)
    for constraint in inspector.get_unique_constraints("push_subscriptions"):
        if constraint["column_names"] == ["expo_push_token"]:
            op.drop_constraint(constraint["name"], "push_subscriptions", type_="unique")
            break
    op.drop_column("push_subscriptions", "expo_push_token")
    op.drop_column("push_subscriptions", "platform")
