"""add notifications.attempts/next_retry_at

Revision ID: ad53f9776b9b
Revises: b3f7d1a6e2c8
Create Date: 2026-09-03 00:00:00.000000

Hand-written (not autogenerated) — same reason as the other migrations in
this project. Guarded with an existence check — same reason as
``d4f8b2e6c9a3``: ``0001_bootstrap`` builds from the *live* ORM models, so
on a fresh database these columns already exist.

Item "notificação falhada é terminal, sem retry" — a transient delivery
failure (SES/Expo/WebPush blip) used to mark a Notification ``FAILED`` for
good; the delivery cycle only ever re-queried ``PENDING``. See
``workers/notification_pipeline.py``.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import inspect

revision: str = "ad53f9776b9b"
down_revision: str | None = "b3f7d1a6e2c8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    inspector = inspect(op.get_bind())
    existing = {c["name"] for c in inspector.get_columns("notifications")}
    if "attempts" not in existing:
        op.add_column(
            "notifications",
            sa.Column("attempts", sa.Integer(), nullable=False, server_default="0"),
        )
    if "next_retry_at" not in existing:
        op.add_column(
            "notifications",
            sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        )


def downgrade() -> None:
    op.drop_column("notifications", "next_retry_at")
    op.drop_column("notifications", "attempts")
