"""add deforestation_checks (item DETER)

Revision ID: b3f7d1a6e2c8
Revises: e884730e20e4
Create Date: 2026-08-28 20:00:00.000000

Hand-written (not autogenerated) — same reason as the other migrations in
this project. Guarded with an existence check — ``0001_bootstrap`` builds
from the *live* ORM models, so on a fresh database this table already
exists.

Tenant-scoped, but created *after* the RLS migration (``0b7b9a5dbd11``)
already ran — that migration is never edited retroactively, so this one
applies the exact same ``ENABLE``/``FORCE``/``CREATE POLICY`` sequence to
`deforestation_checks` directly, same idiom as ``d4b8e2f6a9c1`` (api_keys)
and ``e884730e20e4`` (ndvi_images). No new GRANT needed: ``0b7b9a5dbd11``
already set ``ALTER DEFAULT PRIVILEGES`` so any future table is
automatically visible to the app role.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import inspect

revision: str = "b3f7d1a6e2c8"
down_revision: str | None = "e884730e20e4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_CREATE_POLICY_SQL = """
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE tablename = 'deforestation_checks' AND policyname = 'tenant_isolation'
    ) THEN
        EXECUTE 'CREATE POLICY tenant_isolation ON deforestation_checks
            USING (
                current_setting(''app.bypass_rls'', true) = ''on''
                OR tenant_id = NULLIF(current_setting(''app.tenant_id'', true), '''')::uuid
            )
            WITH CHECK (
                current_setting(''app.bypass_rls'', true) = ''on''
                OR tenant_id = NULLIF(current_setting(''app.tenant_id'', true), '''')::uuid
            )';
    END IF;
END $$;
"""


def upgrade() -> None:
    inspector = inspect(op.get_bind())
    if "deforestation_checks" not in inspector.get_table_names():
        op.create_table(
            "deforestation_checks",
            sa.Column("id", sa.Uuid(), primary_key=True),
            sa.Column(
                "tenant_id",
                sa.Uuid(),
                sa.ForeignKey("tenants.id", ondelete="CASCADE"),
                nullable=False,
                index=True,
            ),
            sa.Column(
                "location_id",
                sa.Uuid(),
                sa.ForeignKey("locations.id", ondelete="CASCADE"),
                nullable=False,
                index=True,
            ),
            sa.Column("source", sa.String(length=40), nullable=False),
            sa.Column("checked_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("alert_count", sa.Integer(), nullable=False, server_default="0"),
            sa.Column("alerts_json", sa.Text(), nullable=False, server_default="[]"),
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.func.now(),
                nullable=False,
            ),
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                server_default=sa.func.now(),
                nullable=False,
            ),
            sa.UniqueConstraint(
                "location_id", "source", name="uq_deforestation_check_location_source"
            ),
        )

    op.execute("ALTER TABLE deforestation_checks ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE deforestation_checks FORCE ROW LEVEL SECURITY")
    op.execute(_CREATE_POLICY_SQL)


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON deforestation_checks")
    op.execute("ALTER TABLE deforestation_checks NO FORCE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE deforestation_checks DISABLE ROW LEVEL SECURITY")
    op.drop_table("deforestation_checks")
