"""add satellite_images

Revision ID: b7d4e1f9a2c3
Revises: a1c2e3f4b5d6
Create Date: 2026-08-20 13:30:00.000000

Hand-written (not autogenerated): same reason as the other migrations in
this project — autogenerate picks up PostGIS's own "tiger geocoder" tables
as noise. No Geography column here (bbox is 4 plain floats, not a
polygon/point — the image itself is a rectangle over a fixed extent), so
there's no GIST-index-duplication concern either.

Guarded with an existence check — same reason as ``5e36b6016c06``/
``f53125d00c98``: ``0001_bootstrap`` builds from the *live* ORM models, so
on a fresh database it already creates this table. See ADR-0012.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import inspect

revision: str = "b7d4e1f9a2c3"
down_revision: str | None = "a1c2e3f4b5d6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    if inspect(op.get_bind()).has_table("satellite_images"):
        return
    op.create_table(
        "satellite_images",
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("bbox_lon_min", sa.Float(), nullable=False),
        sa.Column("bbox_lat_min", sa.Float(), nullable=False),
        sa.Column("bbox_lon_max", sa.Float(), nullable=False),
        sa.Column("bbox_lat_max", sa.Float(), nullable=False),
        sa.Column("band", sa.String(length=16), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("png_data", sa.LargeBinary(), nullable=False),
        sa.Column("is_mock", sa.Boolean(), nullable=False),
        sa.Column("experimental", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_satellite_images_captured_at"), "satellite_images", ["captured_at"], unique=False
    )


def downgrade() -> None:
    op.drop_index(op.f("ix_satellite_images_captured_at"), table_name="satellite_images")
    op.drop_table("satellite_images")
