"""add users account-cycle fields (email_verified, terms_accepted_at)

Revision ID: b8f4c2a7e6d1
Revises: ab4b31a9059a
Create Date: 2026-08-27 09:00:00.000000

Hand-written (not autogenerated) — same reason as the other migrations in
this project (PostGIS "tiger geocoder" noise). Guarded with existence
checks — same reason as ``a1c8e5f3d7b2``: ``0001_bootstrap`` builds from
the *live* ORM models, so on a fresh database these columns already exist.
See ADR-0059 (account cycle: email verification, password reset, terms
acceptance, anti-abuse — FASE 8).

Backfill: every existing account with a linked Google sign-in
(``google_sub IS NOT NULL``) is marked ``email_verified = true`` — Google
already verified that email at the time it was linked (see
``auth/router.py::login_google``, which refuses an unverified Google
email outright), so this reflects a real, already-established fact, not a
fabricated one. Every other pre-existing account (password-only) starts
``email_verified = false`` and ``terms_accepted_at = NULL`` — there was no
verification link and no Terms to accept when they registered, and
neither is backfilled to look like something that happened.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import inspect

revision: str = "b8f4c2a7e6d1"
down_revision: str | None = "ab4b31a9059a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    inspector = inspect(op.get_bind())
    existing_columns = {c["name"] for c in inspector.get_columns("users")}

    if "email_verified" not in existing_columns:
        op.add_column(
            "users",
            sa.Column("email_verified", sa.Boolean(), nullable=False, server_default=sa.false()),
        )
        op.execute("UPDATE users SET email_verified = true WHERE google_sub IS NOT NULL")

    if "email_verified_at" not in existing_columns:
        op.add_column(
            "users", sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True)
        )

    if "terms_accepted_at" not in existing_columns:
        op.add_column(
            "users", sa.Column("terms_accepted_at", sa.DateTime(timezone=True), nullable=True)
        )


def downgrade() -> None:
    op.drop_column("users", "terms_accepted_at")
    op.drop_column("users", "email_verified_at")
    op.drop_column("users", "email_verified")
