"""add storm_risks.ai_summary

Revision ID: c3a7f9e1b5d8
Revises: b8f4c2a7e6d1
Create Date: 2026-08-27 12:00:00.000000

Hand-written (not autogenerated) — same reason as the other migrations in
this project (PostGIS "tiger geocoder" noise). Guarded with an existence
check — same reason as ``c4a8f2d6e9b3``: ``0001_bootstrap`` builds from the
*live* ORM models, so on a fresh database this column already exists. See
ADR-0060 (AI-generated risk summary, FASE 9).
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import inspect

revision: str = "c3a7f9e1b5d8"
down_revision: str | None = "b8f4c2a7e6d1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    inspector = inspect(op.get_bind())
    if "ai_summary" not in {c["name"] for c in inspector.get_columns("storm_risks")}:
        op.add_column("storm_risks", sa.Column("ai_summary", sa.Text(), nullable=True))


def downgrade() -> None:
    op.drop_column("storm_risks", "ai_summary")
