"""add users.last_login_at

Revision ID: c4a8f2d6e9b3
Revises: b3f7a9d2e5c1
Create Date: 2026-08-23 21:00:00.000000

Hand-written (not autogenerated) — same reason as the other migrations in
this project (PostGIS "tiger geocoder" noise). Guarded with an existence
check — same reason as ``a1c8e5f3d7b2``: ``0001_bootstrap`` builds from the
*live* ORM models, so on a fresh database this column already exists. See
ADR-0051 (platform-admin aggregate metrics, FASE 28 Fase 3).
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import inspect

revision: str = "c4a8f2d6e9b3"
down_revision: str | None = "b3f7a9d2e5c1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    inspector = inspect(op.get_bind())
    if "last_login_at" not in {c["name"] for c in inspector.get_columns("users")}:
        op.add_column(
            "users", sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True)
        )


def downgrade() -> None:
    op.drop_column("users", "last_login_at")
