"""add locations.boundary_geojson

Revision ID: c7d29f4a8e1b
Revises: a3e8d1c6f4b2
Create Date: 2026-08-21 22:00:00.000000

Hand-written (not autogenerated) — same reason as the other migrations in
this project (PostGIS "tiger geocoder" noise). Guarded with an existence
check — same reason as ``5e36b6016c06``: ``0001_bootstrap`` builds from the
*live* ORM models, so on a fresh database this column already exists. See
ADR-0024 (talhão polygon outline, FASE 27).
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import inspect

revision: str = "c7d29f4a8e1b"
down_revision: str | None = "a3e8d1c6f4b2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    inspector = inspect(op.get_bind())
    if "boundary_geojson" not in {c["name"] for c in inspector.get_columns("locations")}:
        op.add_column("locations", sa.Column("boundary_geojson", sa.Text(), nullable=True))


def downgrade() -> None:
    op.drop_column("locations", "boundary_geojson")
