"""add api_keys (item 1, ADR-0062)

Revision ID: d4b8e2f6a9c1
Revises: c3a7f9e1b5d8
Create Date: 2026-08-27 15:00:00.000000

Hand-written (not autogenerated) — same reason as the other migrations in
this project (PostGIS "tiger geocoder" noise). Guarded with existence
checks — same reason as ``a1c8e5f3d7b2``: ``0001_bootstrap`` builds from
the *live* ORM models, so on a fresh database this table already exists.

Tenant-scoped, but created *after* the RLS migration (``0b7b9a5dbd11``)
already ran and applied its policy to a fixed list of tables — that
migration is never edited retroactively, so this one applies the exact
same ``ENABLE``/``FORCE``/``CREATE POLICY`` sequence to `api_keys`
directly. No new GRANT needed: ``0b7b9a5dbd11`` already set
``ALTER DEFAULT PRIVILEGES`` so any future table is automatically
visible to the app role.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import inspect

revision: str = "d4b8e2f6a9c1"
down_revision: str | None = "c3a7f9e1b5d8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_CREATE_POLICY_SQL = """
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE tablename = 'api_keys' AND policyname = 'tenant_isolation'
    ) THEN
        EXECUTE 'CREATE POLICY tenant_isolation ON api_keys
            USING (
                current_setting(''app.bypass_rls'', true) = ''on''
                OR tenant_id = NULLIF(current_setting(''app.tenant_id'', true), '''')::uuid
            )
            WITH CHECK (
                current_setting(''app.bypass_rls'', true) = ''on''
                OR tenant_id = NULLIF(current_setting(''app.tenant_id'', true), '''')::uuid
            )';
    END IF;
END $$;
"""


def upgrade() -> None:
    inspector = inspect(op.get_bind())
    if "api_keys" not in inspector.get_table_names():
        op.create_table(
            "api_keys",
            sa.Column("id", sa.Uuid(), primary_key=True),
            sa.Column(
                "tenant_id",
                sa.Uuid(),
                sa.ForeignKey("tenants.id", ondelete="CASCADE"),
                nullable=False,
                index=True,
            ),
            sa.Column(
                "user_id",
                sa.Uuid(),
                sa.ForeignKey("users.id", ondelete="CASCADE"),
                nullable=False,
                index=True,
            ),
            sa.Column("name", sa.String(120), nullable=False),
            sa.Column("key_prefix", sa.String(16), nullable=False),
            sa.Column("key_hash", sa.String(64), nullable=False, unique=True),
            sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.func.now(),
                nullable=False,
            ),
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                server_default=sa.func.now(),
                nullable=False,
            ),
        )
        op.create_index("ix_api_keys_key_hash", "api_keys", ["key_hash"], unique=True)

    op.execute("ALTER TABLE api_keys ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE api_keys FORCE ROW LEVEL SECURITY")
    op.execute(_CREATE_POLICY_SQL)


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON api_keys")
    op.execute("ALTER TABLE api_keys NO FORCE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE api_keys DISABLE ROW LEVEL SECURITY")
    op.drop_table("api_keys")
