"""add locations.color

Revision ID: d4f8b2e6c9a3
Revises: c7d29f4a8e1b
Create Date: 2026-08-21 23:00:00.000000

Hand-written (not autogenerated) — same reason as the other migrations in
this project (PostGIS "tiger geocoder" noise). Guarded with an existence
check — same reason as ``5e36b6016c06``: ``0001_bootstrap`` builds from the
*live* ORM models, so on a fresh database this column already exists. See
ADR-0025 (manual talhão color override, FASE 27).
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import inspect

revision: str = "d4f8b2e6c9a3"
down_revision: str | None = "c7d29f4a8e1b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    inspector = inspect(op.get_bind())
    if "color" not in {c["name"] for c in inspector.get_columns("locations")}:
        op.add_column("locations", sa.Column("color", sa.String(length=7), nullable=True))


def downgrade() -> None:
    op.drop_column("locations", "color")
