"""add ndvi_readings

Revision ID: d7b1f4a8c2e6
Revises: c4a8f2d6e9b3
Create Date: 2026-08-24 14:00:00.000000

Hand-written (not autogenerated) — same reason as the other migrations in
this project (PostGIS "tiger geocoder" noise). Guarded with an existence
check — same reason as ``d3e8f1a9c7b2``: ``0001_bootstrap`` builds from the
*live* ORM models, so on a fresh database it already creates this table.
See ADR-0053 (NDVI por talhão, FASE 29).
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import inspect

revision: str = "d7b1f4a8c2e6"
down_revision: str | None = "c4a8f2d6e9b3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    if inspect(op.get_bind()).has_table("ndvi_readings"):
        return
    op.create_table(
        "ndvi_readings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ndvi_mean", sa.Float(), nullable=False),
        sa.Column("valid_pixel_percent", sa.Float(), nullable=False),
        sa.Column("is_mock", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ndvi_readings_tenant_id"), "ndvi_readings", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_ndvi_readings_location_id"), "ndvi_readings", ["location_id"], unique=False
    )
    op.create_index(
        op.f("ix_ndvi_readings_observed_at"), "ndvi_readings", ["observed_at"], unique=False
    )


def downgrade() -> None:
    op.drop_index(op.f("ix_ndvi_readings_observed_at"), table_name="ndvi_readings")
    op.drop_index(op.f("ix_ndvi_readings_location_id"), table_name="ndvi_readings")
    op.drop_index(op.f("ix_ndvi_readings_tenant_id"), table_name="ndvi_readings")
    op.drop_table("ndvi_readings")
