"""add ndvi_images (item "imagem do talhão")

Revision ID: e884730e20e4
Revises: a9cc165e064a
Create Date: 2026-08-28 14:00:00.000000

Hand-written (not autogenerated) — same reason as the other migrations in
this project. Guarded with an existence check — ``0001_bootstrap`` builds
from the *live* ORM models, so on a fresh database this table already
exists.

Tenant-scoped, but created *after* the RLS migration (``0b7b9a5dbd11``)
already ran — that migration is never edited retroactively, so this one
applies the exact same ``ENABLE``/``FORCE``/``CREATE POLICY`` sequence to
`ndvi_images` directly, same idiom as ``d4b8e2f6a9c1`` (api_keys). No new
GRANT needed: ``0b7b9a5dbd11`` already set ``ALTER DEFAULT PRIVILEGES``
so any future table is automatically visible to the app role.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import inspect

revision: str = "e884730e20e4"
down_revision: str | None = "a9cc165e064a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_CREATE_POLICY_SQL = """
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE tablename = 'ndvi_images' AND policyname = 'tenant_isolation'
    ) THEN
        EXECUTE 'CREATE POLICY tenant_isolation ON ndvi_images
            USING (
                current_setting(''app.bypass_rls'', true) = ''on''
                OR tenant_id = NULLIF(current_setting(''app.tenant_id'', true), '''')::uuid
            )
            WITH CHECK (
                current_setting(''app.bypass_rls'', true) = ''on''
                OR tenant_id = NULLIF(current_setting(''app.tenant_id'', true), '''')::uuid
            )';
    END IF;
END $$;
"""


def upgrade() -> None:
    inspector = inspect(op.get_bind())
    if "ndvi_images" not in inspector.get_table_names():
        op.create_table(
            "ndvi_images",
            sa.Column("id", sa.Uuid(), primary_key=True),
            sa.Column(
                "tenant_id",
                sa.Uuid(),
                sa.ForeignKey("tenants.id", ondelete="CASCADE"),
                nullable=False,
                index=True,
            ),
            sa.Column(
                "location_id",
                sa.Uuid(),
                sa.ForeignKey("locations.id", ondelete="CASCADE"),
                nullable=False,
                index=True,
            ),
            sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("png_data", sa.LargeBinary(), nullable=False),
            sa.Column("is_mock", sa.Boolean(), nullable=False, server_default=sa.false()),
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.func.now(),
                nullable=False,
            ),
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                server_default=sa.func.now(),
                nullable=False,
            ),
            sa.UniqueConstraint("location_id", name="uq_ndvi_image_location"),
        )

    op.execute("ALTER TABLE ndvi_images ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE ndvi_images FORCE ROW LEVEL SECURITY")
    op.execute(_CREATE_POLICY_SQL)


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON ndvi_images")
    op.execute("ALTER TABLE ndvi_images NO FORCE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE ndvi_images DISABLE ROW LEVEL SECURITY")
    op.drop_table("ndvi_images")
