"""add locations.parent_location_id and locations.crop

Revision ID: f2a7c4e9b1d6
Revises: 6ad9dda7d22c
Create Date: 2026-08-21 20:00:00.000000

Hand-written (not autogenerated) — same reason as the other migrations in
this project (PostGIS "tiger geocoder" noise). Guarded with existence
checks — same reason as ``5e36b6016c06``: ``0001_bootstrap`` builds from
the *live* ORM models, so on a fresh database these columns already exist.
See ADR-0022 (talhão / plot support, FASE 26).
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import inspect

revision: str = "f2a7c4e9b1d6"
down_revision: str | None = "6ad9dda7d22c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    inspector = inspect(op.get_bind())
    existing_columns = {c["name"] for c in inspector.get_columns("locations")}

    if "parent_location_id" not in existing_columns:
        op.add_column("locations", sa.Column("parent_location_id", sa.Uuid(), nullable=True))
        op.create_foreign_key(
            "fk_locations_parent_location_id_locations",
            "locations",
            "locations",
            ["parent_location_id"],
            ["id"],
            ondelete="CASCADE",
        )
    if "crop" not in existing_columns:
        op.add_column("locations", sa.Column("crop", sa.String(length=60), nullable=True))

    existing_indexes = {i["name"] for i in inspector.get_indexes("locations")}
    if "ix_locations_parent_location_id" not in existing_indexes:
        op.create_index(
            op.f("ix_locations_parent_location_id"),
            "locations",
            ["parent_location_id"],
            unique=False,
        )


def downgrade() -> None:
    # Hardening ADR-0031: on a database bootstrapped from the frozen-DDL
    # baseline (0001_bootstrap), this FK was created by the ORM relationship
    # and got Postgres's own auto-generated name
    # (``locations_parent_location_id_fkey``), not the hand-picked name this
    # migration's upgrade() used to create it
    # (``fk_locations_parent_location_id_locations``) — that branch of
    # upgrade() is skipped entirely whenever the column already exists. Look
    # the FK up by column instead of assuming either fixed name.
    inspector = inspect(op.get_bind())
    op.drop_index(op.f("ix_locations_parent_location_id"), table_name="locations")
    op.drop_column("locations", "crop")
    for fk in inspector.get_foreign_keys("locations"):
        if fk["constrained_columns"] == ["parent_location_id"]:
            op.drop_constraint(fk["name"], "locations", type_="foreignkey")
            break
    op.drop_column("locations", "parent_location_id")
