"""add zarc_risk_windows

Revision ID: f2b8d4e6a1c9
Revises: a3c7e9f1b4d6
Create Date: 2026-08-27 15:10:00.000000

Hand-written (not autogenerated) — same reason as the other migrations in
this project (PostGIS "tiger geocoder" noise). Guarded with an existence
check — ``0001_bootstrap`` builds from the *live* ORM models, so on a
fresh database this table already exists. See ADR-0069 (ZARC planting
window, item ZARC). No RLS: this is global government reference data,
same category as ``weather_sources``/``radar_frames`` (see the RLS
migration ``0b7b9a5dbd11``'s own list of tables explicitly left out).
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import inspect
from sqlalchemy.dialects import postgresql

revision: str = "f2b8d4e6a1c9"
down_revision: str | None = "a3c7e9f1b4d6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    if inspect(op.get_bind()).has_table("zarc_risk_windows"):
        return
    op.create_table(
        "zarc_risk_windows",
        sa.Column("geocodigo", sa.String(length=10), nullable=False),
        sa.Column("uf", sa.String(length=2), nullable=False),
        sa.Column("municipio", sa.String(length=120), nullable=False),
        sa.Column("cultura", sa.String(length=80), nullable=False),
        sa.Column("cod_ciclo", sa.Integer(), nullable=False),
        sa.Column("cod_solo", sa.Integer(), nullable=False),
        sa.Column("safra_ini", sa.Integer(), nullable=False),
        sa.Column("safra_fin", sa.Integer(), nullable=False),
        sa.Column("portaria", sa.String(length=200), nullable=True),
        sa.Column("decendios", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_zarc_risk_windows_geocodigo"), "zarc_risk_windows", ["geocodigo"], unique=False
    )
    op.create_index(
        op.f("ix_zarc_risk_windows_cultura"), "zarc_risk_windows", ["cultura"], unique=False
    )
    op.create_index(
        "ix_zarc_lookup", "zarc_risk_windows", ["geocodigo", "cultura", "cod_solo"], unique=False
    )


def downgrade() -> None:
    op.drop_index("ix_zarc_lookup", table_name="zarc_risk_windows")
    op.drop_index(op.f("ix_zarc_risk_windows_cultura"), table_name="zarc_risk_windows")
    op.drop_index(op.f("ix_zarc_risk_windows_geocodigo"), table_name="zarc_risk_windows")
    op.drop_table("zarc_risk_windows")
